Modified source directives with return values for lsp tool compatibility.

diff --git a/backup-suite/archive-file-system b/backup-suite/archive-file-system
--- a/backup-suite/archive-file-system
+++ b/backup-suite/archive-file-system
@@ -1,17 +1,23 @@
 #!/usr/bin/env bash
 
 # shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.
+# shellcheck disable=SC2181 # Check exit code directly with e.g. `if mycmd;`, not indirectly with `$?`.
 
 readonly SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 readonly PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
 readonly BASH_LIBS_DIR="$PROJECT_ROOT/lib"
 
 # shellcheck source=../lib/result_type_lib.bash
-source "$BASH_LIBS_DIR/result_type_lib.bash" || exit 1
+source "$BASH_LIBS_DIR/result_type_lib.bash"
+(($? == 0 )) || exit 1
+
 # shellcheck source=../lib/fsa_lib.bash
-source "$BASH_LIBS_DIR/fsa_lib.bash" || exit 1
+source "$BASH_LIBS_DIR/fsa_lib.bash"
+(($? == 0 )) || exit 1
+
 # shellcheck source=../lib/command_line_lib.bash
-source "$BASH_LIBS_DIR/command_line_lib.bash" || exit 1
+source "$BASH_LIBS_DIR/command_line_lib.bash"
+(($? == 0 )) || exit 1
 
 show_help() {
     local command_name="${1##*/}"
